# Generated by Django 4.2.3 on 2024-12-02 06:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('entry_date', models.DateField(auto_created=True, default=datetime.date(2024, 12, 2))),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('entry_details', models.CharField(max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SomeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_number', models.IntegerField()),
                ('a_word', models.CharField(max_length=50, null=True)),
                ('a_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_details', models.CharField(max_length=500)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethinginteractive.booking')),
            ],
        ),
    ]
